# docker-compose up -d

version: '3'

services:
  app:
    build: .
    hostname: localhost
    restart: always
    ports:
    - '443:443'
    - '80:80'
    - '22:22'
    volumes:
    - ~/docker/gitlab/gitlab-ce-ja-9.0.4/config:/etc/gitlab
    - ~/docker/gitlab/gitlab-ce-ja-9.0.4/logs:/var/log/gitlab
    - ~/docker/gitlab/gitlab-ce-ja-9.0.4/data:/var/opt/gitlab
