version: '3'

services:
  app:
    build: .
    hostname: localhost
    restart: always
    ports:
    - '@HTTP_PORT@:80'
    volumes:
    - ./config:/etc/gitlab
    - ./logs:/var/log/gitlab
    - ./data:/var/opt/gitlab
