translations:

# Ruby
- name: 'rb'
  parallel-group: 'group2'
  src: 'app/**/*.rb'
  skip-patterns:
  # Lines that does not contain quotes
  - !!js/regexp /^(?!.*['"]).+$/
  - !!js/regexp /^[^']*('([^a-zA-Z0-9]*|[a-z]+(-[a-z]+)+)'[^']*)+$/
  - !!js/regexp /^[^"]*("([^a-zA-Z0-9]*|[a-z]+(-[a-z]+)+)"[^"]*)+$/
  # Comments and lines that consists of reserved keywords
  - !!js/regexp /^\s*(?:#.*|(?:require|include|class|render|before_action) .*|private|end)?$/

  conditionals:
    - insert:
        at: begin
        value: encodingHeader

  named-patterns:
  - name: sthWasSuccessfullyDone
    pattern: "(notice: ['\"]|alert: ['\"]|flash\\[[^\\]]+\\] = ['\"]){obj}s? (?:was|were) successfully {done}\\.?(['\"])"
    replace: "$1${sthWasSuccessfullyDone}$2"
    args:
    - replace: '${{objKey}}'
    - replace: '${{doneKey}}'
    params: ['obj', 'objKey', 'done', 'doneKey']
  - name: sthNamedWasSuccessfullyDone
    pattern: "(notice: ['\"]|alert: ['\"]|flash\\[[^\\]]+\\] = ['\"]){obj} ([^ ]*) was(?: successfully)? {done}\\.?(['\"])"
    replace: "$1${sthWasSuccessfullyDone}$3"
    args:
    - replace: '${{objKey}} $2 '
    - replace: '${{doneKey}}'
    params: ['obj', 'objKey', 'done', 'doneKey']
  - name: successfullyDone
    pattern: '"Successfully {done}"'
    replace: '"${successfullyDone}"'
    args:
    - replace: '${{doneKey}}'
    params: ['done', 'doneKey']
  - name: errorOccurredObjWasNotDone
    pattern: "alert: \"Error occurred. {obj}s? (?:was|were) not {done}\\.?\""
    replace: "alert: \"${errorOccurredObjWasNotDone}\""
    args:
    - replace: '${{objKey}}'
    - replace: '${{doneKey}}'
    params: ['obj', 'objKey', 'done', 'doneKey']
  - name: sthCountsDone
    pattern: "\"([^\"]*) {obj} {done}\""
    replace: "\"${sthCountsDone}\""
    args:
    - '$1'
    - '${{objKey}}'
    - '${{doneKey}}'
  - name: quotedWord
    pattern: "(\"){word}?\"|('){word}?'"
    replace: '$1$2${{key}}$1$2'
    exclude: "(?:\\s+when .* then|type == ['\"]{word}?['\"]|type: ['\"{word}?['\"]|.* class_name: )"
    params: ['word', 'key']

  patterns:
  # Normal, non-named patterns
  - pattern: "'Application settings saved successfully'"
    replace: "'${applicationSettingsSavedSuccessfully}'"
  - pattern: '"Are you sure you want to leave \"#{group}\" group?"'
    replace: '"${areYouSureYouDoSomething}"'
    args:
    - replace: '${leaveSth}'
      args:
      - '\"#{group}\"'
  - pattern: "\"Service is unknown or it doesn't exist\""
    replace: "\"${serviceIsUnknownOrItDoesntExist}\""
  - pattern: '"Groups"'
    replace: '"${group}"'
  - pattern: '"Users"'
    replace: '"${user}"'
  - pattern: "alert: 'You must provide a valid current password'"
    replace: "alert: '${youMustProvideAValidCurrentPassword}'"
  - pattern: "notice: 'Password successfully changed'"
    replace: "notice: '${passwordSuccessfullyChanged}'"
  - pattern: "Password was successfully updated. Please login with it"
    replace: "${passwordWasSuccessfullyUpdatedPleaseLoginWithIt}"
    match-once: true
  - pattern: "notice: 'We sent you an email with reset password instructions'"
    replace: "notice: '${weSentYouAnEmailWithResetPasswordInstructions}'"
  - pattern: "Please create a password for your new account."
    replace: '${pleaseCreateAPasswordForYourNewAccount}'
  - pattern: "Failed to update profile. #{messages}"
    replace: "${failedToUpdateProfileAndMessages}"
  - pattern: "Your changes have been successfully committed"
    replace: "${yourChangesHaveBeenSuccessfullyCommitted}"
  - pattern: "Could not create Wiki Repository at this time. Please try again later."
    replace: "${couldNotCreateWikiRepositoryAtThisTimePleaseTryAgainLater}"
    match-once: true
  - pattern: "Page not found"
    replace: "${pageNotFound}"
  - pattern: "Account successfully removed."
    replace: "${accountSuccessfullyRemoved}"
  - pattern: "Leave edit mode?\\nAll unsaved changes will be lost."
    replace: "${leaveEditModeAllUnsavedChangesWillBeLost}"
  - pattern: "Browse File »"
    replace: "${browseSth} »"
    args:
    - replace: '${file}'
  - pattern: "Browse Dir »"
    replace: "${browseSth} »"
    args:
    - replace: '${directory}'
  - pattern: "Browse Code »"
    replace: "${browseSth} »"
    args:
    - replace: '${code}'
  - pattern: "View file @"
    replace: "${viewFileAt}"
  - pattern: !!js/regexp /"Filter by ([^"]+)"/
    replace: '"${filterBySth}"'
    args:
    - '$1'
  - pattern: !!js/regexp /"([^"]*) issues updated"/
    replace: "\"${sthCountsDone}\""
    args:
    - '$1'
    - '${issue}'
    - '${update}'
  - pattern: !!js/regexp /The snippet is visible only (?:for|to) me./
    replace: '${theSnippetIsVisibleOnlyForMe}'
  - pattern: !!js/regexp /The snippet is visible (?:for|to) any logged in user./
    replace: '${theSnippetIsVisibleForAnyLoggedInUser}'
  - pattern: !!js/regexp /^(\s+haml_concat ")The snippet can be accessed"\n\s+haml_concat "without any"\n\s+haml_concat "authentication."$/m
    replace: '$1${theSnippetCanBeAccessedWithoutAnyAuthentication}"'
    match-once: true
  - pattern: "The snippet can be accessed without any authentication."
    replace: '${theSnippetCanBeAccessedWithoutAnyAuthentication}'
  - pattern: 'Add an SSH key to your profile<br>to pull or push via SSH.'
    replace: '${addAnSshKeyToYourProfileToPullOrPushViaSsh}'
  - pattern: !!js/regexp /\s{6}opened. "Open"\n\s{4}\}/m
    replace: "      opened: \"${open}\",\n      closed: \"${closed}\",\n      merged: \"${merged}\",\n      all: \"${all}\"\n    }"
  - pattern: 'Group was removed.'
    replace: '${groupWasRemoved}'
  - pattern: 'New Group'
    replace: '${newGroup}'
  - pattern: 'New password'
    replace: '${newPassword}'
  - pattern: 'Failed to update profile'
    replace: '${failedToUpdateProfile}'
  - pattern: !!js/regexp /Are you sure you want to remove ([^\s]+) from ([^\s]+)\?/
    replace: '${areYouSureYouWantToRemoveAFromB}'
    args:
    - '$1'
    - '$2'
  - pattern: !!js/regexp /Are you sure you want to revoke the invitation for ([^\s]+) to join ([^\s]+)\?/
    replace: '${areYouSureYouWantToRevokeTheInvitationForAToJoinB}'
    args:
    - '$1'
    - '$2'
    match-once: true
  - pattern: 'Status changed to closed'
    replace: '${statusChangedToClosed}'
  - pattern: 'Access to group was granted'
    replace: '${accessToGroupWasGranted}'
  - pattern: 'Account was created for you'
    replace: '${accountWasCreatedForYou}'
  - pattern: 'Email was added to your account'
    replace: '${emailWasAddedToYourAccount}'
  - pattern: 'SSH key was added to your account'
    replace: '${sshKeyWasAddedToYourAccount}'
  - pattern: 'Invalid repository path'
    replace: '${invalidRepositoryPath}'
  - pattern: "Can't check your ability to create project"
    replace: '${cantCheckYourAbilityToCreateProject}'
  - pattern: 'Your changes could not be committed, because the file name '
    replace: '${yourChangesCouldNotBeCommittedBecauseTheFileName}'
  - pattern: 'Your changes could not be committed because a file with the same name already exists'
    replace: '${yourChangesCouldNotBeCommittedBecauseAFileWithTheSameNameAlreadyExists}'
  - pattern: !!js/regexp /(\s+body = ')Milestone ('\n\s+body \+= milestone.nil\? \? ')removed('\s:\s")changed to (#{milestone.title})(")/
    replace: '${milestoneRemovedChangedTo}'
    args:
    - '$1'
    - '$2'
    - '$3'
    - '$4'
    - '$5'
  - pattern: 'should be a valid url'
    replace: '${shouldBeAValidUrl}'
  - pattern: !!js/regexp /Your project limit is ([^\s]+) projects! Please contact your administrator to increase it/
    replace: '${yourProjectLimitIsProjectsPleaseContactYourAdministratorToIncreaseIt}'
    args:
    - '$1'
    match-once: true
  - pattern: 'commits_text = "#{total_count} commit".pluralize(total_count)'
    replace: 'commits_text = "#{total_count} ${commit}"'
  - pattern: !!js/regexp /body = "Added (#{commits_text}):\\n\\n"/
    replace: 'body = "${addedSth}:\n\n"'
    args:
    - '$1'
  - pattern: 'Assignee removed'
    replace: '${assigneeRemoved}'
  - pattern: !!js/regexp /Reassigned to (@#{assignee.username})/
    replace: '${reassignedTo}'
    args:
    - '$1'
  - pattern: 'No Milestone'
    replace: '${noMilestone}'

  # Named patterns
  - name: sthWasSuccessfullyDone
    params:
    - {obj: 'Broadcast Message', objKey: broadcastMessage, done: created, doneKey: create}
    - {obj: Group, objKey: group, done: created, doneKey: create}
    - {obj: Group, objKey: group, done: updated, doneKey: update}
    - {obj: Group, objKey: group, done: deleted, doneKey: delete}
    - {obj: User, objKey: user, done: created, doneKey: create}
    - {obj: User, objKey: user, done: added, doneKey: add}
    - {obj: User, objKey: user, done: updated, doneKey: update}

    - {obj: User, objKey: user, done: 'removed from group', doneKey: removeFromGroup }
    - {obj: Hook, objKey: hook, done: created, doneKey: create}
    - {obj: Project, objKey: project, done: forked, doneKey: fork}
    - {obj: Username, objKey: username, done: changed, doneKey: change}
    - {obj: Wiki, objKey: wiki, done: updated, doneKey: update}
    - {obj: Page, objKey: page, done: deleted, doneKey: delete}
    - {obj: Profile, objKey: profile, done: updated, doneKey: update}
    - {obj: Token, objKey: token, done: updated, doneKey: update}
  - name: sthNamedWasSuccessfullyDone
    params:
    - {obj: Group, objKey: group, done: created, doneKey: create}
    - {obj: Group, objKey: group, done: updated, doneKey: update}
    - {obj: Group, objKey: group, done: deleted, doneKey: delete}
    - {obj: Project, objKey: project, done: created, doneKey: create}
    - {obj: Project, objKey: project, done: updated, doneKey: update}
    - {obj: Project, objKey: project, done: deleted, doneKey: delete}
  - name: successfullyDone
    params:
    - {done: blocked, doneKey: block}
    - {done: unblocked, doneKey: unblock}
  - name: errorOccurredObjWasNotDone
    params:
    - {obj: User, objKey: user, done: blocked, doneKey: block}
    - {obj: User, objKey: user, done: unblocked, doneKey: unblock}
  - name: quotedWord
    params:
    - {word: 'Branch(?:es)', key: branch}
    - {word: 'Tags', key: tag}
    - {word: 'Search', key: search}
    - {word: 'Search snippets', key: searchSnippets}
    - {word: 'Search in this project', key: searchInThisProject}
    - {word: 'Search in this group', key: searchInThisGroup}
    - {word: 'Aug 21, 2011 9:23pm', key: timestampAug212011923pm}
    - {word: 'Open', key: open}
    - {word: 'Edit', key: edit}
    - {word: 'Preview', key: preview}
    - {word: 'Preview changes', key: previewChanges}
    - {word: 'Groups', key: group}
    - {word: 'Users', key: user}
    - {word: 'Inline', key: inline}
    - {word: 'Unassigned', key: unassigned}

- name: 'rb:application'
  parallel-group: 'group1'
  src: 'config/application.rb'
  skip-patterns:
  # Empty or comments
  - !!js/regexp /(?:^\s*$|^\s*#)/
  patterns:
  - pattern: !!js/regexp /^    config.i18n.enforce_available_locales = false/
    replace: '${configI18nLocale}'
    exclude: '# done'
