translations:

# Haml
- name: 'haml:shortcuts'
  parallel-group: 'group1'
  src: 'app/views/help/_shortcuts.html.haml'
  skip-patterns:
  # Tag or class that are not followed by any words
  - !!js/regexp /^\s*[\.%][^\s]+$/
  # Empty lines and Ruby codes: comments, render with 1 param,
  # and else/if/unless with zero or one word.
  # Or insertion codes that has no quotation characters
  - !!js/regexp /^\s*(?:$|-[^'"]*$|= render [^,]*$|- ?(?:#.*|(?:if|unless) [^ ]*)$|=[^'"]+$)/
  - !!js/regexp /^\s*(\.key .*|\\\/)$/
  patterns:
  - pattern: "Go to projects"
    replace: '${shortcutsGoToProjects}'
  - pattern: "Go to the activity feed"
    replace: '${shortcutsGoToTheActivityFeed}'
  - pattern: "Go to issues"
    replace: '${shortcutsGoToIssues}'
  - pattern: "Go to merge requests"
    replace: '${shortcutsGoToMergeRequests}'
  - pattern: "Go to the project's home page"
    replace: '${shortcutsGoToTheProjectsHomePage}'
  - pattern: "Go to the project's activity feed"
    replace: '${shortcutsGoToTheProjectsActivityFeed}'
  - pattern: "Go to files"
    replace: '${shortcutsGoToFiles}'
  - pattern: "Go to commits"
    replace: '${shortcutsGoToCommits}'
  - pattern: "Go to jobs"
    replace: '${goToJobs}'
  - pattern: "Go to network graph"
    replace: '${shortcutsGoToNetworkGraph}'
  - pattern: "Go to graphs"
    replace: '${shortcutsGoToGraph}'
  - pattern: "Go to snippets"
    replace: '${shortcutsGoToSnippets}'
  - pattern: "Go to issue boards"
    replace: '${goToIssueBoards}'
  - pattern: "Keyboard Shortcuts"
    replace: '${keyboardShortcuts}'
  - pattern: "Global Shortcuts"
    replace: '${globalShortcuts}'
  - pattern: "Focus Filter"
    replace: '${focusFilter}'
  - pattern: 'Focus Search'
    replace: '${focusSearch}'
  - pattern: 'Finding Project File'
    replace: '${findingProjectFile}'
  - pattern: 'Go to file permalink'
    replace: '${gotoFilePermalink}'
  - pattern: "Show/hide this dialog"
    replace: '${showHideThisDialog}'
  - pattern: "Toggle Markdown preview"
    replace: '${toggleMarkdownPreview}'
  - pattern: "Edit last comment (when focused on an empty textarea)"
    replace: '${editLastCommentWhenFocusedOnAnEmptyTextarea}'
  - pattern: "Project Files browsing"
    replace: '${projectFilesBrowsing}'
  - pattern: 'Project File'
    replace: '${projectFile}'
  - pattern: "Move selection up"
    replace: '${moveSelectionUp}'
  - pattern: "Move selection down"
    replace: '${moveSelectionDown}'
  - pattern: "Open Selection"
    replace: '${openSelection}'
  - pattern: "Go back"
    replace: '${goBack}'
  - pattern: "Global Dashboard"
    replace: '${globalDashboard}'
  - pattern: "Go to finding file"
    replace: '${goToFindingFile}'
  - pattern: "New issue"
    replace: '${newIssue}'
  - pattern: "Project"
    replace: '${project}'
  - pattern: "Issues"
    replace: '${issue}'
  - pattern: "Network Graph"
    replace: '${networkGraph}'
  - pattern: "Scroll left"
    replace: '${scrollLeft}'
  - pattern: "Scroll right"
    replace: '${scrollRight}'
  - pattern: "Scroll up"
    replace: '${scrollUp}'
  - pattern: "Scroll down"
    replace: '${scrollDown}'
  - pattern: "Scroll to top"
    replace: '${scrollToTop}'
  - pattern: "Scroll to bottom"
    replace: '${scrollToBottom}'
  - pattern: "Change assignee"
    replace: '${changeAssignee}'
  - pattern: "Change milestone"
    replace: '${changeMilestone}'
  - pattern: "Reply (quoting selected text)"
    replace: '${replyQuotingSelectedText}'
  - pattern: "Edit issue"
    replace: '${editIssue}'
  - pattern: "Change Label"
    replace: '${changeLabel}'
  - pattern: "Merge Requests"
    replace: '${mergeRequest}'
  - pattern: "Edit merge request"
    replace: '${editMergeRequest}'
