translations:

# JavaScript
- name: 'js:jquery.timeago'
  parallel-group: 'group1'
  src: 'app/assets/javascripts/lib/jquery.timeago.js'
  patterns:
  - insert:
      at: end
      value: jQueryTimeago

- name: 'js'
  parallel-group: 'group2'
  src: 'app/assets/javascripts/**.js*'
  skip-patterns:
  # Lines that does not contain quotes
  - !!js/regexp /^(?!.*\$\('[^']*'\))(?!.*['"]).+$/
  # Quoted strings don't require translation: symbols, css-id or css-class, digits, true/false (single quote)
  - !!js/regexp /^[^']*('([^a-zA-Z0-9]*|[.#]?[a-z]+([-_][a-z]+)+|[0-9.]+|true|false)'[^']*)+$/
  # Quoted strings don't require translation: symbols, css-id or css-class, digits, true/false (double quote)
  - !!js/regexp /^[^"]*("([^a-zA-Z0-9]*|[.#]?[a-z]+([-_][a-z]+)+|[0-9.]+|true|false)"[^"]*)+$/
  # Quotes are only included in known function parameters: $('*'), data('*'), require('*')
  - !!js/regexp /^[^'"]*(\$|data|require)\(['"][^'"]*['"]\)[^'"]*$/
  # Quotes are only included in jQuery function parameters: $(*).on('*'), $(*).off('*'), .on('*'), ...
  - !!js/regexp /^([^'"]*(\$(\([^\)]*\)|[a-z][A-Za-z]+)|form|\.parent\(\))|\s*)\.(on|off|is|attr|prop|data|addClass|removeClass|toggleClass|hasClass|find|bind|closest|parents|tooltip|trigger)\(['"][^'"]*['"](,\s['"][^'"]*['"])?[^'"]*$/
  - !!js/regexp /^([^'"]*(\$(\([^\)]*\)|[a-z][A-Za-z]+)|form|\.parent\(\))|\s*)(\.(on|off|is|attr|prop|data|addClass|removeClass|toggleClass|hasClass|find|bind|closest|parents|tooltip|trigger)\(['"][^'"]*['"]\))+[^'"]*$/
  # jQuery function parameter
  - !!js/regexp /^\s*(dataType|type):\s['"][^'"]*['"],?$/
  # known function fragments
  - !!js/regexp /^\s*(window|document)\.(addEventListener|createElement)\(['"][^'"]*['"](,\s['"][^'"]*['"])?[^'"]*$/
  # Empty
  - !!js/regexp /^\s*$/
  # Comments
  - !!js/regexp /^\s*\/\//
  # Paths
  - !!js/regexp /^\s*[a-z][A-Za-z]+:\s"\/[^"]*",?$/
  named-patterns:
  - name: doubleQuoted
    pattern: "\"{word}\""
    replace: "\"${{key}}\""
    params: ['word', 'key']
  patterns:
  - pattern: "Nothing to preview."
    replace: "${nothingToPreview}"
  - pattern: "Loading..."
    replace: "${loading}"
  - pattern: 'Any Label'
    replace: '${anyLabel}'
  - pattern: 'Any Milestone'
    replace: '${anyMilestone}'
  - pattern: 'Any namepspace'
    replace: '${anyNamespace}'
  - pattern: 'Any User'
    replace: '${anyUser}'
  - pattern: "'Unassigned'"
    replace: "'${unassigned}'"
  - pattern: 'No due date'
    replace: '${noDueDate}'
  - pattern: 'No Label'
    replace: '${noLabel}'
  - pattern: 'No Milestone'
    replace: '${noMilestone}'
  - pattern: 'No contributions'
    replace: '${noContributions}'
  - pattern: 'No assignee'
    replace: '${noAssignee}'
  - pattern: 'assign yourself'
    replace: '${assignYourself}'
  - pattern: 'You need to be logged in.'
    replace: '${youNeedToBeLoggedIn}'
  - pattern: 'Something went wrong on our end.'
    replace: '${somethingWentWrongOnOurEnd}'
  - name: doubleQuoted
    params:
    - {word: 'Search for a user', key: searchForAUser}
