translations:

# Markdown
- name: 'md:permissions'
  parallel-group: 'group3'
  src: 'doc/**/permission*.md'
  skip-patterns:
  - !!js/regexp /(^#+|^\s*$|^[^a-zA-Z]+$|^\s*```|^---)/
  patterns:
  - pattern: '| Action'
    replace: '| ${action}'
  - pattern: '| Create new issue'
    replace: '| ${createNewIssue}'
  - pattern: '| Leave comments'
    replace: '| ${leaveComments}'
  - pattern: '| Pull project code'
    replace: '| ${pullProjectCode}'
  - pattern: '| Download project'
    replace: '| ${downlaodProject}'
  - pattern: '| Create code snippets'
    replace: '| ${createCodeSnippets}'
  - pattern: '| Manage issue tracker'
    replace: '| ${manageIssueTracker}'
  - pattern: '| Manage labels'
    replace: '| ${manageLabels}'
  - pattern: '| Manage merge requests'
    replace: '| ${manageMergeRequests}'
  - pattern: '| Create new merge request'
    replace: '| ${createNewMergeRequests}'
  - pattern: '| Create new branches'
    replace: '| ${createNewBranches}'
  - pattern: '| Push to non-protected branches'
    replace: '| ${pushToNonProtectedBranches}'
  - pattern: '| Force push to non-protected branches'
    replace: '| ${forcePushToNonProtectedBranches}'
  - pattern: '| Remove non-protected branches'
    replace: '| ${removeNonProtectedBranches}'
  - pattern: '| Add tags'
    replace: '| ${addTags}'
  - pattern: '| Write a wiki'
    replace: '| ${writeAWiki}'
  - pattern: '| Create new milestones'
    replace: '| ${createNewMilestones}'
  - pattern: '| Add new team members'
    replace: '| ${addNewTeamMembers}'
  - pattern: '| Push to protected branches'
    replace: '| ${pushToProtectedBranches}'
  - pattern: '| Enable/disable branch protection'
    replace: '| ${enableDisableBranchProtection}'
  - pattern: '| Turn on/off prot. branch push for devs'
    replace: '| ${turnOnOffProtBranchPushForDevs}'
  - pattern: '| Rewrite/remove git tags'
    replace: '| ${rewriteRemoveGitTags}'
  - pattern: '| Edit project'
    replace: '| ${editProject}'
  - pattern: '| Add deploy keys to project'
    replace: '| ${addDeployKeysToProject}'
  - pattern: '| Configure project hooks'
    replace: '| ${configureProjectHooks}'
  - pattern: '| Switch visibility level'
    replace: '| ${switchVisibilityLevel}'
  - pattern: '| Transfer project to another namespace'
    replace: '| ${transferProjectToAnotherNamespace}'
  - pattern: '| Remove project'
    replace: '| ${removeProject}'
  - pattern: '| Force push to protected branches'
    replace: '| ${forcePushToProtectedBranches}'
  - pattern: '| Remove protected branches'
    replace: '| ${removeProtectedBranches}'
  - pattern: !!js/regexp /In order for a group to appear as public and be browsable, it must contain at\nleast one public project\./
    replace: '${inOrderForAGroupToAppearAsPublicAndBeBrowsableItMustContainAtLeastOnePublicProject}'
    complete-pattern: true
  - pattern: 'Any user can remove themselves from a group, unless they are the last Owner of the group.'
    replace: '${anyUserCanRemoveThemselvesFromAGroupUnlessTheyAreTheLastOwnerOfTheGroup}'
    complete-pattern: true
  - pattern: '| Browse group'
    replace: '| ${browseGroup}'
  - pattern: '| Edit group'
    replace: '| ${editGroup}'
  - pattern: '| Create project in group'
    replace: '| ${createProjectInGroup}'
  - pattern: '| Manage group members'
    replace: '| ${manageGroupMembers}'
  - pattern: '| Remove group'
    replace: '| ${removeGroup}'
